spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/places_and_events'
    username: postgres
    password: password
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: validate
  jackson:
    time-zone: UTC
server:
  port: '8080'
servlet:
  context-path: /api/v1.0
logging:
  level:
    web: '''DEBUG'''
