spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/places_and_events_3'
    username: postgres
    password: password
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: UTC
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: false
server:
  error:
    include-message: always
    include-exception: true
    include-binding-errors: always
    include-stacktrace: never
  port: '8080'
  servlet:
    context-path: /api/v1.0
logging:
  level:
    web: debug